# @package player

identity:
  display_name: Qwen3.5 (27B)
  organisation: Qwen
  is_os_model: true
  url: https://huggingface.co/Qwen/Qwen3.5-27B

capabilities:
  player_name: qwen3-5-27b
  tokens_per_image: 266
  structured_output_mode: null
  thinking_method: thinking-out-loud
  include_schema_in_instructions: true
  interaction_location_method: set-of-marks
  coordinate_mode: normalised
  usage_limits:
    input_tokens_limit: 126999
    output_tokens_limit: 1001
  image_dimensions:
    _target_: gptnt.common.image_ops.ImageDimensions
    width: 504
    height: 504

action_predictor:
  agent:
    model:
      _target_: pydantic_ai.models.openai.OpenAIChatModel
      model_name: qwen35
    model_settings:
      _target_: pydantic_ai.models.openai.OpenAIChatModelSettings
      _convert_: all
      max_tokens: 1000

observation_handler:
  image_resizer:
    _target_: gptnt.processors.image_resizer.ImageResizer
    target_width: ${player.capabilities.image_dimensions.width}
    target_height: ${player.capabilities.image_dimensions.height}
