# @package player

defaults:
  - _self_

capabilities:
  player_name: test-defuser
  tokens_per_image: 200
  structured_output_mode: native
  include_schema_in_instructions: true
  interaction_location_method: set-of-marks
  thinking_method: inner-monologue
  usage_limits:
    input_tokens_limit: 200000
    output_tokens_limit: 64000

identity:
  display_name: Test Defuser
  organisation: GPTNT
  is_os_model: false
  url: null

action_predictor:
  agent:
    retries: 0
    model:
      _target_: gptnt.players.dummy_models.DummyDefuserModel
