# @package player.action_predictor.agent.model

provider:
  _target_: pydantic_ai.providers.gateway.gateway_provider
  _args_:
    - google-vertex
  http_client:
    _target_: gptnt.core.common.base_client.cached_retrying_async_http_client
    provider: gateway/google-vertex
