# @package player

defaults:
  - _self_

_target_: gptnt.app.controller.Controller

dialogue_space_client:
  _target_: gptnt.dialogue_space.client.DialogueSpaceClient.from_host_and_port
  host: ${dialogue_space_host}
  port: ${dialogue_space_port}

view: ???

gradio_launch_kwargs:
  share: false
  # server_port: ???
