# @package player

defaults:
  - human/_default
  - _self_

view:
  _target_: gptnt.players.human.views.expert.ExpertPlayerView
  pdf_endpoint: https://www.bombmanual.com/print/KeepTalkingAndNobodyExplodes-BombDefusalManual-v1.pdf
