# @package player.agent
instructions: >
  # Instructions

  ## Scenario

  We are playing Keep Talking and Nobody Explodes (KTANE).

  ### Available Actions

  At each turn, you can take one of the actions described below. All actions must be formatted in valid JSON. Do not provide any part of your response outside of the JSON, or I will not receive it.

  There are two types of game interactions:

  1. Actions without location requirements

  {"command": "interact_game", "action": {GAME_ACTION}}

  where {GAME_ACTION} can be one of:

  * `rotate_left` (-90° rotation)
  * `rotate_right` (90° rotation)
  * `flip` (180° rotation)
  * `roll_up` (90° roll upward)
  * `roll_down` (90° roll downward)
  * `zoom_out` (return to full bomb view from a zoomed module)
  * `release` (release a hold action)

  Rotating left and right, flipping, as well as rolling up or down and zooming out are your navigation actions.

  2. Actions with location requirements

  {"command": "interact_game", "action": {GAME_ACTION}, "location": {LOCATION}}

  where {GAME_ACTION} can be one of:

  * `click_release` (click on location and release immediately)
  * `hold` (click and hold on location)

  and {LOCATION} is the numeric ID of the interactive object as shown on the image.

  ### Thoughts

  If you are thinking through a problem step by step, output these thoughts in the format "thoughts": "{THOUGHTS}". You need to replace {THOUGHTS} with your thoughts. For instance:

  * for actions without location requirements: {"command": "interact_game", "action": {GAME_ACTION}, "thoughts": {THOUGHTS}}
  * for actions with location requirements:  {"command": "interact_game", "action": {GAME_ACTION}, "location": {LOCATION}, "thoughts": {THOUGHTS}}

  If you do not have any thoughts, you can provide "thoughts": "", or leave out the "thoughts" entirely.

  ## Response Formatting

  You may only perform ONE action per turn and you need to follow the JSON format of the available actions. Your entire response should be a single valid JSON object.

  ALWAYS use one of the valid JSON formats as they are parsed by an incredibly strict validator - one incorrect character will result in your action going wrong.
