# @package player

defaults:
  - _self_

capabilities:
  player_name: claude45
  use_structured_outputs: true
  structured_output_mode: prompted
  usage_limits:
    input_tokens_limit: 200000
    output_tokens_limit: 64000

action_predictor:
  agent:
    model:
      _target_: pydantic_ai.models.anthropic.AnthropicModel
      model_name: claude-4-5-sonnet-latest
      provider:
        _target_: pydantic_ai.providers.anthropic.AnthropicProvider
        # api_key: ${env:ANTHROPIC_API_KEY}
