# @package player

defaults:
  - _self_

metadata:
  player_name: claude37

agent:
  model:
    _target_: pydantic_ai.models.anthropic.AnthropicModel
    model_name: claude-3-7-sonnet-latest
    provider:
      _target_: pydantic_ai.providers.anthropic.AnthropicProvider
      # api_key: ${env:ANTHROPIC_API_KEY}
