# @package player

defaults:
  - _self_

_target_: ???

metadata:
  _target_: gptnt.players.base_player.PlayerMetadata
  player_type: ai

  player_name: ???
  player_role: ???

agent:
  _target_: pydantic_ai.Agent

  model: ???
  output_type: ???
  system_prompt: ???

  model_settings:
    _target_: pydantic_ai.settings.ModelSettings
    temperature: 0.0
    top_p: 1.0

usage_limits:
  _target_: pydantic_ai.usage.UsageLimits
  request_limit: 1000
  request_tokens_limit: null
  response_tokens_limit: null
  total_tokens_limit: null
