# @package player

defaults:
  - default
  - _self_

metadata:
  player_name: gemini-25

agent:
  model:
    _target_: pydantic_ai.models.gemini.GeminiModel
    model_name: gemini-2.5-flash-preview-04-17
    provider:
      _target_: pydantic_ai.providers.google_vertex.GoogleVertexProvider
      service_account_file: "storage/keys/gemini.json"
