# @package player

defaults:
  - _self_

capabilities:
  player_name: gemini-3
  structured_output_mode: prompted
  include_schema_in_instructions: true
  usage_limits:
    input_tokens_limit: 1048576
    output_tokens_limit: 65536

action_predictor:
  agent:
    model:
      _target_: pydantic_ai.models.google.GoogleModel
      model_name: gemini-3-pro-preview
      provider:
        _target_: pydantic_ai.providers.google.GoogleProvider

    model_settings:
      _target_: pydantic_ai.models.google.GoogleModelSettings
      _convert_: all
      # max_tokens: 1000
      google_thinking_config:
        _target_: pydantic_ai.models.google.ThinkingConfigDict
        thinking_level: low
      google_video_resolution: "MEDIA_RESOLUTION_MEDIUM"
      google_safety_settings:
        - category: HARM_CATEGORY_HARASSMENT
          threshold: BLOCK_NONE
        - category: HARM_CATEGORY_DANGEROUS_CONTENT
          threshold: BLOCK_NONE
        - category: HARM_CATEGORY_HATE_SPEECH
          threshold: BLOCK_NONE
        - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
          threshold: BLOCK_NONE
        - category: HARM_CATEGORY_CIVIC_INTEGRITY
          threshold: BLOCK_NONE
