# @package player

defaults:
  - default
  - _self_

metadata:
  player_name: gemini-2

agent:
  output_type:
    variant: "gemini"

  model:
    _target_: pydantic_ai.models.gemini.GeminiModel
    model_name: gemini-2.0-flash
    provider:
      _target_: pydantic_ai.providers.google_vertex.GoogleVertexProvider
      service_account_file: "storage/keys/gemini.json"

  model_settings:
    _target_: pydantic_ai.models.gemini.GeminiModelSettings
    _convert_: all
    gemini_safety_settings:
      - _target_: pydantic_ai.models.gemini.GeminiSafetySettings
        category: HARM_CATEGORY_HARASSMENT
        level: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        level: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        level: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        level: BLOCK_NONE
      - category: HARM_CATEGORY_CIVIC_INTEGRITY
        level: BLOCK_NONE
