# @package player

defaults:
  - _self_

capabilities:
  player_name: gpt5
  use_structured_outputs: true
  structured_output_mode: prompted
  usage_limits:
    input_tokens_limit: 400000
    output_tokens_limit: 128000

action_predictor:
  agent:
    model:
      _target_: pydantic_ai.models.openai.OpenAIModel
      model_name: gpt-5
      provider:
        _target_: pydantic_ai.providers.azure.AzureProvider
        # api_key: ${env:AZURE_OPENAI_API_KEY}
        # api_version: ${env:AZURE_OPENAI_API_VERSION}
        # endpoint: ${env:AZURE_OPENAI_ENDPOINT}
    model_settings:
      _target_: pydantic_ai.models.openai.OpenAIModelSettings
      _convert_: all
      max_tokens: 1000
      openai_reasoning_effort: minimal
      openai_reasoning_summary: null
