# @package player

defaults:
  - vllm
  - _self_

metadata:
  player_name: internvl3-38b

agent:
  output_type:
    variant: "gemini"

  model:
    model_name: OpenGVLab/InternVL3-38B-AWQ
    provider:
      base_url: http://localhost:11434/v1
