# @package player

defaults:
  - _vllm
  - _self_

capabilities:
  player_name: internvl35-38b
  supports_structured_output: true
  desired_image_dimensions:
    _target_: gptnt.common.image_ops.ImageDimensions
    width: 448
    height: 448

action_predictor:
  agent:
    model:
      model_name: OpenGVLab/InternVL3_5-38B-MPO
      provider:
        base_url: http://localhost:11435/v1
    model_settings:
      _target_: pydantic_ai.models.openai.OpenAIResponsesModelSettings
      _convert_: all
      max_tokens: 1000

observation_handler:
  image_resizer:
    _target_: gptnt.processors.image_resizer.ImageResizer
    target_width: ${player.capabilities.desired_image_dimensions.width}
    target_height: ${player.capabilities.desired_image_dimensions.height}
