# @package player

capabilities:
  player_name: internvl35
  structured_output_mode: null
  thinking_method: thinking-out-loud
  include_schema_in_instructions: true
  interaction_location_method: set-of-marks
  coordinate_mode: normalised
  usage_limits:
    input_tokens_limit: 39959
    output_tokens_limit: 1001
  image_dimensions:
    _target_: gptnt.common.image_ops.ImageDimensions
    width: 448
    height: 448

action_predictor:
  agent:
    model:
      _target_: pydantic_ai.models.openai.OpenAIChatModel
      model_name: internvl35

    model_settings:
      _target_: pydantic_ai.models.openai.OpenAIChatModelSettings
      _convert_: all
      max_tokens: 1000
      extra_body:
        chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n'}}{% if message['content'] is string %}{{ message['content'] }}{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' %}{{ '<image>\n' }}{% elif content['type'] == 'video' %}{{ '<video>\n' }}{% elif content['type'] == 'text' %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}{{'<|im_end|>\n'}}{% endfor %}{% if add_generation_prompt %}{{'<|im_start|>assistant\n\n' }}{% endif %}"

observation_handler:
  image_resizer:
    _target_: gptnt.processors.image_resizer.ImageResizer
    target_width: ${player.capabilities.image_dimensions.width}
    target_height: ${player.capabilities.image_dimensions.height}
