# @package player

defaults:
  - vllm
  - _self_

metadata:
  player_name: internvl3-38b

agent:
  model:
    model_name: OpenGVLab/InternVL3-38B
    provider:
      base_url: http://localhost:11434/v1
