# @package player

defaults:
  - vllm
  - _self_

metadata:
  player_name: internvl3-8b
  supports_structured_output: false

agent:
  model:
    model_name: OpenGVLab/InternVL3-8B
    provider:
      base_url: http://localhost:11434/v1
