# @package player

defaults:
  - vllm
  - _self_

metadata:
  player_name: qwen25vl-32b
  supports_structured_output: false

agent:
  model:
    model_name: Qwen/Qwen2.5-VL-32B-Instruct-AWQ
    provider:
      base_url: http://localhost:11434/v1
  model_settings:
    _target_: pydantic_ai.models.openai.OpenAIResponsesModelSettings
    _convert_: all
    max_tokens: 1000
