# @package player

defaults:
  - vllm
  - _self_

metadata:
  player_name: qwen25vl-3b

agent:
  model:
    model_name: Qwen/Qwen2.5-VL-3B-Instruct-AWQ
    provider:
      base_url: http://localhost:11434/v1
