# @package player

defaults:
  - _vllm
  - _self_

capabilities:
  player_name: qwen3vl-32b
  supports_structured_output: false

action_predictor:
  agent:
    model:
      model_name: Qwen/Qwen3-VL-32B-Instruct
      provider:
        base_url: http://localhost:11434/v1
    model_settings:
      _target_: pydantic_ai.models.openai.OpenAIResponsesModelSettings
      _convert_: all
      max_tokens: 1000
