# @package player

defaults:
  - _self_

capabilities:
  player_name: test-oracle
  structured_output_mode: native
  include_schema_in_instructions: true
  interaction_location_method: set-of-marks

action_predictor:
  agent:
    retries: 0
    model:
      _target_: gptnt.players.dummy.models.MagicDefuserModel
