# @package player

defaults:
  - _self_

capabilities:
  player_name: test-expert
  supports_structured_output: true

action_predictor:
  agent:
    retries: 0
    model:
      _target_: gptnt.players.dummy.models.DummyExpertModel
