# @package player

defaults:
  - _self_

capabilities:
  player_name: test-oracle
  use_structured_outputs: true
  structured_output_mode: native

action_predictor:
  agent:
    retries: 0
    model:
      _target_: gptnt.players.dummy.models.MagicDefuserModel
