# @package player

defaults:
  - _self_

metadata:
  player_name: test-defuser
  supports_structured_output: true

agent:
  retries: 0
  model:
    _target_: gptnt.players.dummy.models.DummyDefuserModel
