# @package _global_

defaults:
  - _self_
  - anchors
  - hydra: default

  - experiment/mission_condition: single_module
  - experiment/communication_style: sync
  - experiment/pairing: no_expert

  - experiment/player_specs@defuser_protocol: solo_defuser
  - experiment/player_specs@expert_protocol: none

  - experiment: null

  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

task_name: generate_experiments

# list of players to generate experiments for
players:
  all:
    - gpt5
    - claude46
    - gemini-3
    - internvl35
    - qwen35

defuser_protocol: ???
expert_protocol: ???
communication_style: ???

mission_generator:
  _target_: gptnt.experiments.generation.missions.MissionGenerator
  seed: 10
  num_seeds_per_mission: ???
  config: ???

experiment_generator:
  _target_: gptnt.experiments.generation.experiments.ExperimentGenerator
  condition: ???
  defuser_protocol: ${defuser_protocol}
  expert_protocol: ${expert_protocol}
  attempts_per_mission: 1

pairing_generator:
  _target_: gptnt.experiments.generation.pairing.PairingGenerator
  pairing_type: ???
  best_model: null
  all_players: ${players.all}
