# @package _global_

defaults:
  - _self_
  - hydra: default

  - player: ai/defuser_mdp_som
  - model: claude37
  - system_prompt: defuser

  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

task_name: evaluation
experiment_manager_client:
  _target_: gptnt.api.experiment_manager_client.ExperimentManagerClient
  url: "http://localhost:8099"
