# @package _global_

defaults:
  - _self_
  - hydra: default

  - player: expert
  - model: gpt4o

  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

task_name: evaluation

dialogue_space_host: localhost
dialogue_space_port: 1234

ktane_client_host: localhost
ktane_client_port: 1235
