# @package _global_

defaults:
  - _self_
  - hydra: default

  - model: test_defuser

  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

task_name: evaluation

player:
  _target_: gptnt.services.player.supervisor.PlayerSupervisor
  _partial_: true

  redis:
    _target_: redis.Redis

  capabilities:
    _target_: gptnt.players.specification.PlayerCapabilities
    player_type: ai
    player_name: ???
    use_structured_outputs: ???

  experiment_recorder:
    _target_: gptnt.players.metrics.wandb.WandbExperimentPlayerRecorder
    capabilities: ${player.capabilities}
    wandb_entity: ${oc.env:WANDB_ENTITY,gptnt}
    wandb_project: ${oc.env:WANDB_PROJECT,gptnt}

  action_predictor:
    _target_: gptnt.players.ai.action_predictor.ActionPredictor
    capabilities: ${player.capabilities}
    agent:
      _target_: pydantic_ai.Agent

      retries: 0

      model: ???

      model_settings:
        _target_: pydantic_ai.settings.ModelSettings
        _convert_: all
        temperature: 0.0
        top_p: 1.0

  observation_handler:
    _target_: gptnt.players.observation_handler.ObservationHandler
    image_resizer: null
    set_of_marks_painter:
      _target_: gptnt.processors.set_of_marks.SetOfMarksHandler
      add_labels: true
      add_mask_outline: true
      mark_type: alphabet
      annotation_text_params:
        _target_: gptnt.processors.labels.drawing.AnnotationTextParams
        font: 2
        font_scale: 0.7
        thickness: 1
        space_between_boxes: 2
      annotation_background_params:
        _target_: gptnt.processors.labels.drawing.AnnotationBackgroundParams
        padding: 3
        alpha: 1
      mask_drawing_params:
        _target_: gptnt.processors.set_of_marks.MaskDrawingParams
        mask_thickness: 1
        soft_mask_alpha: 0.1
        bw_outside_mask: False
        # In pixels, or null
        mask_highlight_size: null
