# @package player

defaults:
  - _default
  - _self_

_target_: ???

game_client:
  _target_: gptnt.ktane.client.KtaneClient
  client:
    _target_: httpx.AsyncClient
    base_url: "http://localhost:1245"

agent:
  output_type:
    _target_: gptnt.players.ai.output_type.get_defuser_output_type
