# @package player

defaults:
  - _defuser
  - _self_

agent:
  output_type:
    variant: "set_of_marks"

game_client:
  set_of_marks_painter:
    _target_: gptnt.processors.set_of_marks.SetOfMarksHandler
    annotation_text_params:
      _target_: gptnt.processors.labels.drawing.AnnotationTextParams
      font: 2
      font_scale: 0.7
      thickness: 1
      space_between_boxes: 2
    annotation_background_params:
      _target_: gptnt.processors.labels.drawing.AnnotationBackgroundParams
      padding: 3
      alpha: 0.75
    mask_drawing_params:
      _target_: gptnt.processors.set_of_marks.MaskDrawingParams
      mask_thickness: 1
      soft_mask_alpha: 0.5
      bw_outside_mask: False
      color_dependent_brighten_factor: 0.4

    add_labels: true
    add_mask_outline: true

should_save_images: false
