# @package player

defaults:
  - _self_

_target_: ???

metadata:
  _target_: gptnt.players.base_player.PlayerMetadata
  player_type: ai

tracker:
  _target_: gptnt.players.metrics.PlayerEpisodeTracker
  wandb_init_kwargs:
    project: gptnt
    entity: gptnt

should_reflect_on_game_at_end: false
