# @package _global_

defaults:
  - /manual@suite.manual_profile: ???

suite:
  _target_: gptnt.experiments.suite.definition.Suite
  name: ???
  revision: 1
  modality: [vision, language]
  missions_path: ???
  manual_rule_seed: 1
  defuser_protocol:
    _target_: gptnt.players.specification.PlayerProtocol
    role: defuser
    communication_style: ???
    is_playing_alone: false
    include_manual: false
  expert_protocol:
    _target_: gptnt.players.specification.PlayerProtocol
    role: expert
    communication_style: ???
    is_playing_alone: false
    include_manual: true
  matchup:
    _target_: gptnt.experiments.suite.definition.SuiteMatchup
    pairing_type: ???
