# @package _global_

defaults:
  - /manual@suite.manual_build.profile: vanilla

suite:
  _target_: gptnt.experiments.suite.core.Suite
  name: single-self-async
  revision: 2
  modality: [vision, language]
  missions_path: configs/missions/single_module
  defuser_protocol:
    _target_: gptnt.players.specification.PlayerProtocol
    role: defuser
    communication_style: async
    is_playing_alone: false
    include_manual: false
  expert_protocol:
    _target_: gptnt.players.specification.PlayerProtocol
    role: expert
    communication_style: async
    is_playing_alone: false
    include_manual: true
  matchup:
    _target_: gptnt.experiments.suite.core.SuiteMatchup
    pairing_type: with_self
  manual_build:
    _target_: gptnt.ktane.manuals.definition.compose_manual_build_definition
    language: en
    rule_seed: 1
    compiler_schema: gptnt.manual.v1
    profile:
      _target_: gptnt.ktane.manuals.profile.ManualProfile
