# @package _global_

defaults:
  - /manual@suite.manual_profile: vanilla

suite:
  _target_: gptnt.experiments.suite.definition.Suite
  name: single-parametric-sync
  revision: 2
  modality: [vision, language]
  missions_path: configs/missions/single_module
  manual_rule_seed: 1764
  defuser_protocol:
    _target_: gptnt.players.specification.PlayerProtocol
    role: defuser
    communication_style: sync
    is_playing_alone: true
    include_manual: false
  expert_protocol: null
  matchup:
    _target_: gptnt.experiments.suite.definition.SuiteMatchup
    pairing_type: no_expert
  manual_profile:
    _target_: gptnt.ktane.manuals.profile.ManualProfile
